baseURL: "https://joeshans21.github.io/" 
title: John (Joe) Shanahan
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: Courses
          url: courses/
          weight: 2
        - name: Data
          url: data/
          weight: 3 

params:
    description: "I am a second-year student at UNC Chapel Hill from Raleigh NC, pursuing a double major in Computer Science and Statistics & Analytics. This past summer I had the privilege to at Modern Capital Inc. as a Quantitative Developer Intern. I'm currently a ULA for COMP 211 and am conducting ML research with applications to Biology."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: John (Joe) Shanahan
          subtitle: "I am a second-year student at UNC Chapel Hill from Raleigh NC, pursuing a double major in Computer Science and Statistics & Analytics. This past summer I had the privilege to work at Modern Capital Inc. as a Quantitative Developer Intern. I'm currently a ULA for COMP 211 and am conducting ML research with applications to Biology."
          imageUrl: "picture.jpeg"
          imageWidth: 540
          imageHeight: 540
          imageTitle: John (Joe) Shanahan
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Data
              url: data/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:jshans@unc.edu
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: GitHub
          url: https://github.com/JoeShans21
        - name: LinkedIn
          url: https://linkedin.com/in/johnshans/

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "John (Joe) Shanahan"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
